"""Background scheduler that fires recurring analyses.

A single worker thread wakes once a minute, walks every enabled
schedule in the store, and decides whether to enqueue a new analysis.
The decision logic is split into pure functions (``should_fire_*``)
so the test suite can drive them with frozen ``now`` / ``last_run_at``
values without involving threads or yfinance.

Intentional design choices:

  * One worker thread, not a pool. Schedule firing is cheap; the work
    itself is done by ``AnalysisRunner`` which is already serialised.
  * No persistent "next fire time" stored alongside the schedule —
    instead, every wake recomputes the answer from
    ``last_run_at`` + the current clock. Means a process restart never
    misses a daily fire and the on-disk schema stays minimal.
  * Volatility schedules call yfinance from the worker thread. We
    throttle via ``check_interval_minutes`` so a cluster of schedules
    can't hammer yahoo. Failures are logged and skipped — a missing
    quote shouldn't kill the daily schedule running next to it.
"""

from __future__ import annotations

import logging
import threading
from datetime import date, datetime, timedelta, timezone
from typing import Any, Dict, Optional

from .runner import AnalysisRunner
from .schedules import ScheduleStore
from .storage import AnalysisStore

logger = logging.getLogger(__name__)


def _detect_asset_type(ticker: str) -> str:
    """Local import to avoid the api↔scheduler circular dependency.

    ``detect_asset_type`` lives in ``server.api`` so the FastAPI layer
    can validate ticker inputs without pulling in scheduler code; we
    can't ``from .api import detect_asset_type`` at module level here
    because ``api`` imports ``BackgroundScheduler`` from this module.
    A function-level import is the simplest break in that cycle.
    """
    from .api import detect_asset_type as _impl

    return _impl(ticker)


# How often the worker thread wakes up. 60 s is granular enough for
# minute-precision daily schedules and infrequent enough that the
# loop is essentially free CPU-wise.
DEFAULT_TICK_SECONDS = 60.0


# ---------------------------------------------------------------------------
# Pure decision logic — no I/O, fully unit-testable
# ---------------------------------------------------------------------------


def _parse_iso(ts: Optional[str]) -> Optional[datetime]:
    """Tolerant ISO-8601 parser. Returns ``None`` for None/empty/invalid."""
    if not ts:
        return None
    try:
        # ``fromisoformat`` accepts our ``isoformat()`` output verbatim.
        d = datetime.fromisoformat(ts)
    except ValueError:
        return None
    # Treat naive timestamps as UTC — every persisted timestamp in
    # this codebase is generated by ``_utcnow_iso``, but we accept
    # legacy strings without the ``+00:00`` suffix to be safe.
    if d.tzinfo is None:
        d = d.replace(tzinfo=timezone.utc)
    return d


def should_fire_daily(
    *,
    now_utc: datetime,
    last_run_at: Optional[str],
    fire_hour_utc: int,
    fire_minute_utc: int,
    weekdays_only: bool = True,
) -> bool:
    """Decide whether a ``daily_after_close`` schedule should fire now.

    Fires at most once per day, on or after the configured target
    time. Crucially: if the worker misses the target minute (server
    sleep, restart, GC pause), the next tick after the target will
    still fire — we compare against the target *time*, not the
    instant we woke up.
    """
    if weekdays_only and now_utc.weekday() >= 5:  # Sat=5, Sun=6
        return False

    target = now_utc.replace(
        hour=fire_hour_utc, minute=fire_minute_utc, second=0, microsecond=0
    )
    if now_utc < target:
        return False

    last = _parse_iso(last_run_at)
    if last is None:
        return True
    # Fire when the most recent run pre-dates today's target time.
    # This naturally throttles to "once per day" without needing to
    # store a separate "fired today" flag.
    return last < target


def should_fire_volatility(
    *,
    now_utc: datetime,
    last_run_at: Optional[str],
    last_check_at: Optional[str],
    threshold_pct: float,
    throttle_hours: int,
    check_interval_minutes: int,
    intraday_return_pct: Optional[float],
) -> bool:
    """Decide whether a ``volatility_trigger`` schedule should fire.

    Three guards layered together so a single big move doesn't keep
    re-firing for hours:

      1. ``check_interval_minutes`` — how often we *poll* yfinance.
         Even a flat market can't trigger more than once per interval.
      2. ``throttle_hours`` — once we fire, the next fire is at least
         this many hours later, regardless of how big the move is.
      3. ``intraday_return_pct`` actually crossing the threshold.

    Returns False (without firing) when the price fetcher returns
    None — typically because yfinance is unreachable or the ticker
    has no quote yet.
    """
    # Poll-throttle. Skip price fetch entirely on subsequent ticks
    # within the polling window.
    last_check = _parse_iso(last_check_at)
    if last_check is not None:
        delta = (now_utc - last_check).total_seconds() / 60.0
        if delta < check_interval_minutes:
            return False

    # Fire-throttle. The poll above already burnt a yfinance call,
    # but firing is the expensive part (kicks an LLM run) so we
    # block on this hard.
    last_fire = _parse_iso(last_run_at)
    if last_fire is not None:
        delta_h = (now_utc - last_fire).total_seconds() / 3600.0
        if delta_h < throttle_hours:
            return False

    if intraday_return_pct is None:
        return False
    return abs(intraday_return_pct) >= threshold_pct


# ---------------------------------------------------------------------------
# Price fetcher (the only part that talks to the network)
# ---------------------------------------------------------------------------


def fetch_intraday_return_pct(ticker: str) -> Optional[float]:
    """Return ``(latest - prior_close) / prior_close * 100`` or None.

    Uses yfinance with a 2-day window so we always have access to
    yesterday's close even if today's session has just opened. If
    yfinance is unavailable or the ticker is unknown, returns None
    so the caller can skip the schedule cleanly.
    """
    try:
        import yfinance as yf
    except ImportError:
        logger.warning("yfinance not installed; volatility checks disabled")
        return None

    try:
        df = yf.download(
            ticker,
            period="2d",
            interval="1m",
            progress=False,
            auto_adjust=False,
            threads=False,
        )
    except Exception:  # noqa: BLE001 — third-party may raise anything
        logger.exception("yfinance intraday fetch failed for %s", ticker)
        return None

    if df is None or df.empty:
        return None
    try:
        col = df["Close"].dropna()
    except KeyError:
        return None
    if col.empty:
        return None

    # Group by trading-day date so we can pick yesterday's last close
    # vs today's most recent print without assuming any particular
    # number of intraday bars.
    by_date: Dict[date, float] = {}
    for ts, val in col.items():
        try:
            scalar = float(val)
        except (TypeError, ValueError):
            try:
                scalar = float(val.iloc[0])  # type: ignore[union-attr]
            except Exception:  # noqa: BLE001
                continue
        d = ts.date() if hasattr(ts, "date") else None
        if d is None:
            continue
        # Last entry per date wins — yfinance returns chronologically
        # ordered rows, so the final assignment is the latest print.
        by_date[d] = scalar

    if len(by_date) < 2:
        return None
    sorted_dates = sorted(by_date.keys())
    prior_close = by_date[sorted_dates[-2]]
    latest = by_date[sorted_dates[-1]]
    if prior_close == 0:
        return None
    return (latest - prior_close) / prior_close * 100.0


# ---------------------------------------------------------------------------
# Scheduler thread
# ---------------------------------------------------------------------------


def _today_iso(now_utc: datetime) -> str:
    return now_utc.date().isoformat()


class BackgroundScheduler:
    """One worker thread, evaluated every minute."""

    def __init__(
        self,
        *,
        analysis_store: AnalysisStore,
        schedule_store: ScheduleStore,
        runner: AnalysisRunner,
        tick_seconds: float = DEFAULT_TICK_SECONDS,
    ) -> None:
        self.analyses = analysis_store
        self.schedules = schedule_store
        self.runner = runner
        self.tick_seconds = tick_seconds
        self._stop = threading.Event()
        self._thread: Optional[threading.Thread] = None
        self._started_lock = threading.Lock()

    # ---- lifecycle ----------------------------------------------------

    def start(self) -> None:
        with self._started_lock:
            if self._thread is not None and self._thread.is_alive():
                return
            self._stop.clear()
            self._thread = threading.Thread(
                target=self._loop, name="schedule-runner", daemon=True
            )
            self._thread.start()

    def stop(self, *, timeout: float = 5.0) -> None:
        self._stop.set()
        if self._thread is not None:
            self._thread.join(timeout=timeout)

    def _loop(self) -> None:
        # Wait briefly before the first pass so an unrelated startup
        # error elsewhere doesn't get tangled up with a fire.
        if self._stop.wait(timeout=2.0):
            return
        while not self._stop.is_set():
            try:
                self.tick(datetime.now(timezone.utc))
            except Exception:  # noqa: BLE001
                logger.exception("Scheduler tick crashed")
            if self._stop.wait(timeout=self.tick_seconds):
                return

    # ---- one pass over all schedules ----------------------------------

    def tick(self, now_utc: datetime) -> None:
        """Public so tests (and a future ``/run-now-all`` admin
        endpoint) can drive a single pass deterministically."""
        for schedule in self.schedules.list():
            if not schedule.get("enabled", True):
                continue
            try:
                self._evaluate(schedule, now_utc)
            except Exception:  # noqa: BLE001
                logger.exception(
                    "Failed to evaluate schedule %s", schedule.get("id")
                )

    def _evaluate(self, schedule: Dict[str, Any], now_utc: datetime) -> None:
        kind = schedule.get("kind")
        if kind == "daily_after_close":
            self._evaluate_daily(schedule, now_utc)
        elif kind == "volatility_trigger":
            self._evaluate_volatility(schedule, now_utc)
        else:
            logger.warning(
                "Schedule %s has unknown kind %r; skipping",
                schedule.get("id"),
                kind,
            )

    def _evaluate_daily(
        self, schedule: Dict[str, Any], now_utc: datetime
    ) -> None:
        params = schedule.get("params") or {}
        if not should_fire_daily(
            now_utc=now_utc,
            last_run_at=schedule.get("last_run_at"),
            fire_hour_utc=int(params.get("fire_hour_utc", 21)),
            fire_minute_utc=int(params.get("fire_minute_utc", 30)),
            weekdays_only=bool(params.get("weekdays_only", True)),
        ):
            return
        self._fire(schedule, now_utc)

    def _evaluate_volatility(
        self, schedule: Dict[str, Any], now_utc: datetime
    ) -> None:
        params = schedule.get("params") or {}
        check_interval = int(params.get("check_interval_minutes", 15))
        throttle_h = int(params.get("throttle_hours", 6))
        threshold = float(params.get("threshold_pct", 1.5))

        # Pre-check the cheap throttles so we don't spend a yfinance
        # call when we already know we won't fire.
        last_check = _parse_iso(schedule.get("last_check_at"))
        if last_check is not None:
            mins = (now_utc - last_check).total_seconds() / 60.0
            if mins < check_interval:
                return
        last_fire = _parse_iso(schedule.get("last_run_at"))
        if last_fire is not None:
            hours = (now_utc - last_fire).total_seconds() / 3600.0
            if hours < throttle_h:
                # Still mark "checked" so we don't busy-loop on this
                # branch every minute.
                self.schedules.mark_checked(
                    schedule["id"], checked_at=now_utc.isoformat()
                )
                return

        intraday = fetch_intraday_return_pct(schedule["ticker"])
        # Always update last_check_at, even on a missing quote, so the
        # loop respects the polling cadence.
        self.schedules.mark_checked(
            schedule["id"], checked_at=now_utc.isoformat()
        )

        if not should_fire_volatility(
            now_utc=now_utc,
            last_run_at=schedule.get("last_run_at"),
            # Already updated above, but pass ``now`` so the pure
            # function also sees the fresh check time. The pre-check
            # above means this branch only runs when intervals have
            # elapsed, so this is a belt-and-braces guard.
            last_check_at=last_check.isoformat() if last_check else None,
            threshold_pct=threshold,
            throttle_hours=throttle_h,
            check_interval_minutes=check_interval,
            intraday_return_pct=intraday,
        ):
            return
        self._fire(schedule, now_utc)

    # ---- create + queue the analysis ---------------------------------

    def _fire(self, schedule: Dict[str, Any], now_utc: datetime) -> None:
        """Create an analysis from the schedule + push it to the runner."""
        ticker = schedule["ticker"]
        record = self.analyses.create(
            ticker=ticker,
            asset_type=schedule.get("asset_type") or _detect_asset_type(ticker),
            analysis_date=_today_iso(now_utc),
            language=schedule.get("language", "English"),
            max_debate_rounds=int(schedule.get("max_debate_rounds", 3)),
            max_risk_discuss_rounds=int(
                schedule.get("max_risk_discuss_rounds", 3)
            ),
        )
        self.runner.submit(record["id"])
        self.schedules.mark_fired(
            schedule["id"],
            analysis_id=record["id"],
            fired_at=now_utc.isoformat(),
        )
        logger.info(
            "Schedule %s fired (kind=%s ticker=%s analysis=%s)",
            schedule["id"],
            schedule.get("kind"),
            ticker,
            record["id"],
        )


# ---------------------------------------------------------------------------
# One-call helper to seed the default schedules a first-time user wants
# ---------------------------------------------------------------------------


RECOMMENDED_TICKER = "GLD"
RECOMMENDED_DEPTH = 3   # Medium = 3 rounds, matches CLI's middle option


def seed_recommended_schedules(
    schedule_store: ScheduleStore,
    *,
    ticker: str = RECOMMENDED_TICKER,
    language: str = "English",
) -> Dict[str, Dict[str, Any]]:
    """Idempotently create the two recommended schedules.

    Returns a dict ``{"daily": <record>, "volatility": <record>}``
    pointing at the schedules currently on disk for this ticker.
    Callers (the API) wire this behind an explicit user click — we
    don't seed silently on app boot, because that would surprise
    someone who uses a non-GLD ticker.
    """
    asset_type = _detect_asset_type(ticker)
    existing_by_kind: Dict[str, Dict[str, Any]] = {}
    for sched in schedule_store.list():
        if sched.get("ticker") == ticker.upper() and sched.get("kind") in (
            "daily_after_close",
            "volatility_trigger",
        ):
            existing_by_kind.setdefault(sched["kind"], sched)

    out: Dict[str, Dict[str, Any]] = {}
    if "daily_after_close" not in existing_by_kind:
        out["daily"] = schedule_store.create(
            ticker=ticker,
            asset_type=asset_type,
            kind="daily_after_close",
            language=language,
            max_debate_rounds=RECOMMENDED_DEPTH,
            max_risk_discuss_rounds=RECOMMENDED_DEPTH,
        )
    else:
        out["daily"] = existing_by_kind["daily_after_close"]

    if "volatility_trigger" not in existing_by_kind:
        out["volatility"] = schedule_store.create(
            ticker=ticker,
            asset_type=asset_type,
            kind="volatility_trigger",
            language=language,
            max_debate_rounds=RECOMMENDED_DEPTH,
            max_risk_discuss_rounds=RECOMMENDED_DEPTH,
        )
    else:
        out["volatility"] = existing_by_kind["volatility_trigger"]
    return out
